
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-stagiaire
          uri: lb://service-stagiaire
          predicates:
            - Path=/api/stagiaires/**
          filters:
            - StripPrefix=0

  discovery:
    locator:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
